BettingEsport\MatchBundle\Entity\Equipe:
    type: entity
    table: null
    repositoryClass: BettingEsport\MatchBundle\Entity\EquipeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        logo:
            type: string
            length: 255
        listJoueurs:
            type: string
            length: 255
        lien:
            type: string
            length: 255
        infos:
            type: string
            length: 255
    lifecycleCallbacks: {  }
