BettingEsport\MatchBundle\Entity\MatchEquipe:
    type: entity
    table: null
    repositoryClass: BettingEsport\MatchBundle\Entity\MatchEquipeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idEquipe1:
            type: integer
        idEquipe2:
            type: integer
        dateHeureDebut:
            type: datetime
        dateHeureFinParis:
            type: datetime
        resultat:
            type: integer
        lienStream:
            type: string
            length: 255
        coteEquipe1:
            type: integer
        coteEquipe2:
            type: integer
        jeu:
            type: string
            length: 255
    lifecycleCallbacks: {  }
