<?php

namespace BettingEsport\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends EntityRepository
{
}
