<?php

namespace BettingEsport\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchEquipeRepository extends EntityRepository
{
}
